# Generated by Django 6.0.2 on 2026-02-10 07:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_email_verified', models.BooleanField(default=False)),
                ('email_verification_token', models.CharField(blank=True, max_length=100, null=True)),
                ('email_verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('welcome_email_sent', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_premium', models.BooleanField(default=False, help_text='Whether user has premium/paying access')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('institution', models.CharField(blank=True, db_column='university', help_text='Institution name', max_length=300)),
                ('position', models.CharField(blank=True, help_text='Position or role', max_length=200)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClickTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('signup', 'Sign Up'), ('gatekeeper_directory', 'Gatekeeper Directory'), ('gatekeeper_detail', 'Gatekeeper Detail'), ('institution_rankings', 'Institution Rankings'), ('institution_profile', 'Institution Profile'), ('project_detail', 'Project Detail'), ('regional_rankings', 'Regional Rankings'), ('global_institution_rankings', 'Global Institution Rankings'), ('gatekeeper_pdf', 'Gatekeeper PDF Download'), ('regional_pdf', 'Regional PDF Download')], db_index=True, max_length=50)),
                ('page_url', models.CharField(help_text='Full URL path', max_length=500)),
                ('is_authenticated', models.BooleanField(db_index=True, default=False)),
                ('is_premium', models.BooleanField(db_index=True, default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('referer', models.CharField(blank=True, max_length=500)),
                ('country_code', models.CharField(blank=True, help_text='For country-specific pages', max_length=10)),
                ('organization_name', models.CharField(blank=True, help_text='For detail pages', max_length=300)),
                ('region', models.CharField(blank=True, help_text='For regional pages', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who clicked (null for anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='click_tracking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Click Tracking',
                'verbose_name_plural': 'Click Tracking',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['page_type', '-created_at'], name='accounts_cl_page_ty_9062e6_idx'), models.Index(fields=['is_authenticated', 'is_premium', '-created_at'], name='accounts_cl_is_auth_7d0224_idx'), models.Index(fields=['created_at'], name='accounts_cl_created_013f80_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['sent_at'], name='accounts_em_sent_at_cd3fd7_idx')],
            },
        ),
    ]
