# Generated by Django 6.0.2 on 2026-02-10 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_searches_reset_date_user_searches_today'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='position',
        ),
    ]
