# Generated by Django 6.0.2 on 2026-02-09 19:36

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('companies_scraped', models.IntegerField(default=0)),
                ('companies_updated', models.IntegerField(default=0)),
                ('companies_new', models.IntegerField(default=0)),
                ('errors', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nipt', models.CharField(db_index=True, help_text='NIPT/NUIS - unique tax identification number', max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('name_latin', models.CharField(blank=True, max_length=500)),
                ('legal_form', models.CharField(choices=[('shpk', 'Sh.P.K. (LLC)'), ('sha', 'Sh.A. (Joint Stock)'), ('pf', 'Person Fizik (Sole Proprietor)'), ('deg', 'Degë e Shoqërisë së Huaj (Foreign Branch)'), ('other', 'Other')], default='shpk', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('suspended', 'Pezulluar'), ('dissolved', 'Çregjistruar'), ('bankruptcy', 'Falimentuar'), ('in_liquidation', 'Në Likuidim')], default='active', max_length=20)),
                ('nace_code', models.CharField(blank=True, help_text='NACE activity code', max_length=10)),
                ('nace_description', models.TextField(blank=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('capital', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('capital_currency', models.CharField(default='ALL', max_length=5)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('municipality', models.CharField(blank=True, max_length=100)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('raw_pdf_text', models.TextField(blank=True, help_text='Raw extracted text from QKB PDF')),
                ('source_url', models.URLField(blank=True)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='companies_c_search__af2048_gin'), models.Index(fields=['status', 'city'], name='companies_c_status_ce3eeb_idx'), models.Index(fields=['legal_form'], name='companies_c_legal_f_adbefb_idx'), models.Index(fields=['registration_date'], name='companies_c_registr_201684_idx')],
            },
        ),
        migrations.CreateModel(
            name='LegalRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=300)),
                ('role', models.CharField(default='Administrator', max_length=100)),
                ('appointed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='companies.company')),
            ],
            options={
                'indexes': [models.Index(fields=['full_name'], name='companies_l_full_na_a53919_idx')],
            },
        ),
        migrations.CreateModel(
            name='OwnershipChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateField()),
                ('description', models.TextField()),
                ('old_shareholders', models.JSONField(default=list)),
                ('new_shareholders', models.JSONField(default=list)),
                ('source', models.CharField(default='qkb_scrape', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_changes', to='companies.company')),
            ],
            options={
                'ordering': ['-change_date'],
                'indexes': [models.Index(fields=['company', 'change_date'], name='companies_o_company_78747f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareholder_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], max_length=12)),
                ('full_name', models.CharField(blank=True, db_index=True, max_length=300)),
                ('parent_company_name', models.CharField(blank=True, help_text='Name of parent company (even if not yet in our DB)', max_length=500)),
                ('ownership_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Ownership percentage', max_digits=6, null=True)),
                ('share_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholders', to='companies.company')),
                ('parent_company', models.ForeignKey(blank=True, help_text='If shareholder is another company in our DB', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='companies.company')),
            ],
            options={
                'indexes': [models.Index(fields=['full_name'], name='companies_s_full_na_af19f0_idx'), models.Index(fields=['company', 'shareholder_type'], name='companies_s_company_2c373b_idx')],
            },
        ),
    ]
