# Generated by Django 6.0.2 on 2026-02-10 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulletin_number', models.CharField(blank=True, help_text="APP bulletin number (e.g., 'Nr. 5')", max_length=50)),
                ('bulletin_date', models.DateField(blank=True, help_text='Publication date of the bulletin', null=True)),
                ('reference_number', models.CharField(blank=True, db_index=True, help_text='Procedure reference (REF-xxxxx-xx-xx-xx)', max_length=100)),
                ('authority_name', models.CharField(help_text='Contracting authority name', max_length=500)),
                ('authority_type', models.CharField(blank=True, help_text='e.g., SH.A, Ministry, Municipality', max_length=100)),
                ('title', models.TextField(help_text='Procurement object description')),
                ('procedure_type', models.CharField(choices=[('open', 'Procedurë e Hapur'), ('restricted', 'Procedurë e Kufizuar'), ('negotiated', 'Procedurë me Negocim'), ('proposal', 'Kërkesë për Propozim'), ('consultancy', 'Shërbim Konsulence'), ('small_value', 'Vlerë e Vogël'), ('design_contest', 'Konkurs Projektimi'), ('other', 'Other')], default='open', max_length=20)),
                ('status', models.CharField(choices=[('awarded', 'Awarded'), ('cancelled', 'Cancelled'), ('appealed', 'Appealed')], default='awarded', max_length=20)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, help_text='Fondi limit (estimated value in lekë)', max_digits=15, null=True)),
                ('contract_value', models.DecimalField(blank=True, decimal_places=2, help_text='Vlera e kontratës (contract value in lekë, excl. VAT)', max_digits=15, null=True)),
                ('winner_name', models.CharField(help_text='Winner company name as listed in bulletin', max_length=500)),
                ('winner_nipt', models.CharField(blank=True, db_index=True, help_text='Winner NIPT from bulletin', max_length=20)),
                ('contract_date', models.DateField(blank=True, help_text='Date contract was signed', null=True)),
                ('num_bidders', models.PositiveIntegerField(blank=True, help_text='Number of bidders', null=True)),
                ('disqualified_bidders', models.JSONField(blank=True, default=list, help_text='List of disqualified bidders [{name, nipt, reason}]')),
                ('subcontractors', models.JSONField(blank=True, default=list, help_text='List of subcontractors [{name, nipt, value}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('winner_company', models.ForeignKey(blank=True, help_text='Link to company in our DB (auto-linked by NIPT)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders_won', to='companies.company')),
            ],
            options={
                'ordering': ['-bulletin_date', '-contract_date'],
                'indexes': [models.Index(fields=['winner_nipt'], name='companies_t_winner__22bb1b_idx'), models.Index(fields=['authority_name'], name='companies_t_authori_67e21e_idx'), models.Index(fields=['bulletin_date'], name='companies_t_bulleti_222894_idx'), models.Index(fields=['reference_number'], name='companies_t_referen_610f36_idx')],
            },
        ),
    ]
